# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 25
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: true

    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01
      joint1: { trajectory: 0.1, goal: 0.1 }
      joint2: { trajectory: 0.1, goal: 0.1 }

joint_broad:
  ros__parameters:
    publish_rate: 50