# -----------------------------------
controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    kitchen_bot_controller:
      type: diff_drive_controller/DiffDriveController

    kitchen_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster


kitchen_bot_controller:
  ros__parameters:
    left_wheel_names  : ['left_wheel_joint']
    right_wheel_names : ['right_wheel_joint']

    command_interfaces: ["velocity"]
    state_interfaces: ["position", "velocity"]

    publish_rate: 41.2

    pose_covariance_diagonal : [0.00001, 0.00001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.1, 0.1, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    enable_odom_tf: false

    wheel_separation : 0.445208
    wheel_radius : 0.0625

    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier    : 1.0

    cmd_vel_timeout: 0.5
    use_stamped_vel: false

    base_frame_id: base_link
    odom_frame_id: odom

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0 
        has_acceleration_limits: true
        max_acceleration       : 2.0
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.5
        has_acceleration_limits: true
        max_acceleration       : 2.5


kitchen_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    state_publish_rate: 25
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true

    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"]

    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01
      joint1: { trajectory: 0.1, goal: 0.1 }
      joint2: { trajectory: 0.1, goal: 0.1 }

joint_broad:
  ros__parameters:
    publish_rate: 50
