<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="kitchen_bot">
  <xacro:macro name="kitchen_bot"> 
    <xacro:include filename="$(find kitchen_bot_description)/urdf/include/kitchen_bot.gazebo.xacro"/>
    <xacro:include filename="$(find kitchen_bot_description)/urdf/include/common_properties.urdf.xacro" />
    <xacro:include filename="$(find kitchen_bot_description)/urdf/include/transmissions.xacro" />

    <xacro:property name="deg_to_rad" value="0.017453293" />

    <xacro:property name="kitchen_bot_base_inertial_x" value="-0.05" />
    <xacro:property name="kitchen_bot_base_inertial_y" value="0.0" />
    <xacro:property name="kitchen_bot_base_inertial_z" value="0.15" />
    <xacro:property name="kitchen_bot_base_inertial_x_length" value="0.50" />
    <xacro:property name="kitchen_bot_base_inertial_y_length" value="0.30" />
    <xacro:property name="kitchen_bot_base_inertial_z_length" value="0.20" />

    <xacro:property name="kitchen_bot_base_mass" value="77.0" />
    <xacro:property name="kitchen_bot_act_wheel_radius" value="0.0625" />
    <xacro:property name="kitchen_bot_act_wheel_width" value="0.032" />
    <xacro:property name="kitchen_bot_act_wheel_mass" value="1.0" />
    <xacro:property name="kitchen_bot_act_wheel_dx" value="0.037646" />
    <xacro:property name="kitchen_bot_act_wheel_dy" value="0.222604" />

    <xacro:property name="kitchen_bot_caster_wheel_radius" value="0.0625" />
    <xacro:property name="kitchen_bot_caster_wheel_width" value="0.032" />
    <xacro:property name="kitchen_bot_caster_wheel_mass" value="1.0" />
    <xacro:property name="kitchen_bot_caster_wheel_dx" value="-0.0382" />
    <xacro:property name="kitchen_bot_caster_wheel_dy" value="0" />
    <xacro:property name="kitchen_bot_caster_wheel_dz" value="-0.094" />
    <xacro:property name="kitchen_bot_front_caster_wheel_base_dx" value="0.3037" />
    <xacro:property name="kitchen_bot_back_caster_wheel_base_dx"  value="0.3078" />
    <xacro:property name="kitchen_bot_caster_wheel_base_dy" value="0.203" />
    <xacro:property name="kitchen_bot_caster_wheel_base_dz" value="${kitchen_bot_caster_wheel_radius - kitchen_bot_caster_wheel_dz}" />

    <xacro:property name="laser_dx" value="0.392" />
    <xacro:property name="laser_dy" value="0.2358" />

    <link name="base_footprint" />

    <joint name="base_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_link">
      <xacro:box_inertial mass="${kitchen_bot_base_mass}" x="${kitchen_bot_base_inertial_x_length}" y="${kitchen_bot_base_inertial_y_length}" z="${kitchen_bot_base_inertial_z_length}">
        <origin xyz="${kitchen_bot_base_inertial_x + kitchen_bot_act_wheel_dx} ${kitchen_bot_base_inertial_y} ${kitchen_bot_base_inertial_z}" rpy="0 0 0" />
      </xacro:box_inertial>

      <visual>
        <origin xyz="${kitchen_bot_act_wheel_dx} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="$(find kitchen_bot_description)/meshes/kitchen_bot/visual/mir_100_base.stl" />
        </geometry>
        <xacro:insert_block name="material_white" />
      </visual>

      <collision>
        <origin xyz="${kitchen_bot_act_wheel_dx} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="$(find kitchen_bot_description)/meshes/kitchen_bot/collision/mir_100_base.stl" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="base_link">
      <material>Gazebo/White</material>
    </gazebo>

    <xacro:macro name="actuated_wheel" params="locationprefix locationright">
      <joint name="${locationprefix}_wheel_joint" type="continuous">
          <origin xyz="0.0 ${-kitchen_bot_act_wheel_dy * locationright} ${kitchen_bot_act_wheel_radius}" rpy="0 0 0" />
          <parent link="base_link" />
          <child link="${locationprefix}_wheel_link" />
          <axis xyz="0 1 0" />
          <limit effort="100" velocity="20.0" />
      </joint>

      <link name="${locationprefix}_wheel_link">
          <xacro:cylinder_inertial mass="${kitchen_bot_act_wheel_mass}" radius="${kitchen_bot_act_wheel_radius}" length="${kitchen_bot_act_wheel_width}">
              <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
          </xacro:cylinder_inertial>

          <visual>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
              <cylinder radius="${kitchen_bot_act_wheel_radius}" length="${kitchen_bot_act_wheel_width}" />
              </geometry>
              <xacro:insert_block name="material_black" />
          </visual>

          <collision>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
              <cylinder radius="${kitchen_bot_act_wheel_radius}" length="${kitchen_bot_act_wheel_width}" />
              </geometry>
          </collision>
      </link>

      <gazebo reference="${locationprefix}_wheel_link">
          <material>Gazebo/FlatBlack</material>
      </gazebo>
    </xacro:macro>

    <xacro:macro name="caster_wheel" params="locationprefix locationright wheel_base_dx">
      <!-- Caster Hub -->
      <joint name="${locationprefix}_caster_rotation_joint" type="continuous">
          <origin xyz="${wheel_base_dx} ${-kitchen_bot_caster_wheel_base_dy * locationright} ${kitchen_bot_caster_wheel_base_dz}" rpy="0 0 0" />
          <parent link="base_link" />
          <child link="${locationprefix}_caster_rotation_link" />
          <axis xyz="0 0 1" />
          <dynamics damping="0.01" friction="0.0"/>
      </joint>

      <link name="${locationprefix}_caster_rotation_link">
          <inertial>
              <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
              <mass value="0.3097539019" />
              <inertia ixx="0.0005844517978" ixy="0" ixz="0" iyy="0.00052872551237" iyz="0" izz="0.00017923555074" />
          </inertial>

          <visual>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
              <mesh filename="$(find kitchen_bot_description)/meshes/kitchen_bot/visual/caster_wheel_base.stl" />
              </geometry>
              <xacro:insert_block name="material_silver" />
          </visual>

          <collision>
              <origin xyz="0 0 0" rpy="0 0 0" />
              <geometry>
              <mesh filename="$(find kitchen_bot_description)/meshes/kitchen_bot/collision/caster_wheel_base.stl" />
              </geometry>
          </collision>
      </link>

      <gazebo reference="${locationprefix}_caster_rotation_link">
          <material>Gazebo/Grey</material>
      </gazebo>

      <!-- Caster Wheel -->
      <joint name="${locationprefix}_caster_wheel_joint" type="continuous">
          <origin xyz="${kitchen_bot_caster_wheel_dx} ${-kitchen_bot_caster_wheel_dy * locationright} ${kitchen_bot_caster_wheel_dz}" rpy="0 0 0" />
          <parent link="${locationprefix}_caster_rotation_link" />
          <child link="${locationprefix}_caster_wheel_link" />
          <axis xyz="0 1 0" />
      </joint>

      <link name="${locationprefix}_caster_wheel_link">
          <xacro:cylinder_inertial mass="${kitchen_bot_caster_wheel_mass}" radius="${kitchen_bot_caster_wheel_radius}" length="${kitchen_bot_caster_wheel_width}">
              <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
          </xacro:cylinder_inertial>

          <visual>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
              <cylinder radius="${kitchen_bot_caster_wheel_radius}" length="${kitchen_bot_caster_wheel_width}" />
              </geometry>
              <xacro:insert_block name="material_black" />
          </visual>

          <collision>
              <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
              <geometry>
              <cylinder radius="${kitchen_bot_caster_wheel_radius}" length="${kitchen_bot_caster_wheel_width}" />
              </geometry>
          </collision>
      </link>

      <gazebo reference="${locationprefix}_caster_wheel_link">
          <material>Gazebo/FlatBlack</material>
      </gazebo>
    </xacro:macro>

    <!-- wheels -->
    <xacro:actuated_wheel locationprefix="left" locationright="-1"/>
    <xacro:actuated_wheel locationprefix="right" locationright="1"/>
    <xacro:caster_wheel locationprefix="fl" locationright="-1" wheel_base_dx="${kitchen_bot_front_caster_wheel_base_dx + kitchen_bot_act_wheel_dx}"/>
    <xacro:caster_wheel locationprefix="fr" locationright="1" wheel_base_dx="${kitchen_bot_front_caster_wheel_base_dx + kitchen_bot_act_wheel_dx}"/>
    <xacro:caster_wheel locationprefix="bl" locationright="-1" wheel_base_dx="${-kitchen_bot_back_caster_wheel_base_dx + kitchen_bot_act_wheel_dx}"/>
    <xacro:caster_wheel locationprefix="br" locationright="1" wheel_base_dx="${-kitchen_bot_back_caster_wheel_base_dx + kitchen_bot_act_wheel_dx}"/>

    <!-- Camera -->
    <link name="camera_link">
      <pose>0.2 0 0.3 0 0 0</pose>
      <visual name="camera_visual">
        <geometry>
          <box size="0.05 0.05 0.05"/>
        </geometry>
        <xacro:insert_block name="material_white" />
      </visual>
    </link>

    <joint name="camera_joint" type="fixed">
      <parent link="base_link"/>
      <child link="camera_link"/>
      <origin xyz="0.2 0 0.3" rpy="0 0 0"/>
    </joint>

    <gazebo reference="camera_link">
      <sensor name="camera" type="camera">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <camera>
          <horizontal_fov>1.047</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.1</near>
            <far>10</far>
          </clip>
          <save enabled="false"/>
        </camera>
        <update_rate>30</update_rate>
        <always_on>true</always_on>
      </sensor>
    </gazebo>
  </xacro:macro> 
</robot>
